services:
  app:
    image: app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker_application.properties:/app/application.properties:ro
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    restart: always
    volumes:
      - /var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=phuc --password=phuc --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: phuc
      MYSQL_USER: phuc
      MYSQL_PASSWORD: phuc
      MYSQL_DATABASE: url_shortener
    command: ["--bind-address=0.0.0.0"]
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./.docker/data/redis:/data
